name: "iotas-topology"
config:
#  topology.debug: true
  catalog.root.url: ${catalog.root.url}
  local.parser.jar.path: ${parser.jar.path}
  local.notifier.jar.path: ${notifier.jar.path}
  hbase.conf:
    hbase.root.dir: ${hbase.root.dir}
  notification.conf:
    queuehandler.threads: 10
components:
  - id: "zkHosts"
    className: "org.apache.storm.kafka.ZkHosts"
    constructorArgs:
      - ${kafka.spout.zkUrl}

  - id: "spoutConfig"
    className: "org.apache.storm.kafka.SpoutConfig"
    constructorArgs:
      - ref: "zkHosts"
      - ${kafka.spout.topic}
      - ${kafka.spout.zkRoot}
      - ${kafka.spout.id}

  - id: "hBaseMapper"
    className: "com.hortonworks.hbase.ParserOutputHBaseMapper"
    constructorArgs:
      - ${hbase.column.family}

  - id: "recordFormat"
    className: "com.hortonworks.hdfs.IdentityHdfsRecordFormat"

  - id: "syncPolicy"
    className: "org.apache.storm.hdfs.bolt.sync.CountSyncPolicy"
    constructorArgs:
      - ${hdfs.syncPolicyCount}

  - id: "rotationPolicy"
    className: "org.apache.storm.hdfs.bolt.rotation.TimedRotationPolicy"
    constructorArgs:
      - ${hdfs.rotationInterval}
      - SECONDS

  - id: "fileNameFormat"
    className: "org.apache.storm.hdfs.bolt.format.DefaultFileNameFormat"
    configMethods:
      - name: "withPath"
        args:
          - ${hdfs.path}
      - name: "withPrefix"
        args:
          - ${hdfs.name}

# spout definitions
spouts:
  - id: "KafkaSpout"
    className: "org.apache.storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "spoutConfig"

# bolt definitions
bolts:
  - id: "ParserBolt"
    className: "com.hortonworks.bolt.ParserBolt"
    configMethods:
      - name: "withParsedTuplesStreamId"
        args:
          - "parsed_tuples_stream"
      - name: "withUnparsedTuplesStreamId"
        args:
          - "failed_to_parse_tuples_stream"

  - id: "PrinterBolt"
    className: "com.hortonworks.bolt.PrinterBolt"

  - id: "HBaseBolt"
    className: "org.apache.storm.hbase.bolt.HBaseBolt"
    constructorArgs:
      - ${hbase.table}
      - ref: "hBaseMapper"
    configMethods:
      - name: "withConfigKey"
        args:
          - "hbase.conf"

  - id: "DummyRuleBolt"
    className: "com.hortonworks.bolt.DummyRuleBolt"
    parallelism: 1
    configMethods:
      - name: "withConsoleNotificationStream"
        args:
          - "console_stream"
      - name: "withEmailNotificationStream"
        args:
          - "email_stream"

  - id: "ConsoleNotificationBolt"
    className: "com.hortonworks.bolt.notification.NotificationBolt"
    constructorArgs:
          - "console_notifier"
    configMethods:
      - name: "withHBaseConfigKey"
        args:
          - "hbase.conf"

    parallelism: 1

  - id: "EmailNotificationBolt"
    className: "com.hortonworks.bolt.notification.NotificationBolt"
    constructorArgs:
          - "email_notifier"
    configMethods:
      - name: "withHBaseConfigKey"
        args:
          - "hbase.conf"

    parallelism: 1

  - id: "HdfsBolt"
    className: "org.apache.storm.hdfs.bolt.HdfsBolt"
    configMethods:
      - name: "withFsUrl"
        args:
          - ${hdfs.fsUrl}
      - name: "withFileNameFormat"
        args:
          - ref: "fileNameFormat"
      - name: "withRecordFormat"
        args:
          - ref: "recordFormat"
      - name: "withRotationPolicy"
        args:
          - ref: "rotationPolicy"
      - name: "withSyncPolicy"
        args:
          - ref: "syncPolicy"

#stream definitions
streams:
  - name: "kafka --> parser"
    from: "KafkaSpout"
    to: "ParserBolt"
    grouping:
      type: SHUFFLE

  - name: "paser --> printer"
    from: "ParserBolt"
    to: "PrinterBolt"
    grouping:
      type: SHUFFLE
      streamId: "parsed_tuples_stream"

  - name: "paser --> hbase"
    from: "ParserBolt"
    to: "HBaseBolt"
    grouping:
      type: SHUFFLE
      streamId: "parsed_tuples_stream"

  - name: "paser --> hdfs"
    from: "ParserBolt"
    to: "HdfsBolt"
    grouping:
      type: SHUFFLE
      streamId: "failed_to_parse_tuples_stream"

  - name: "paser --> rule"
    from: "ParserBolt"
    to: "DummyRuleBolt"
    grouping:
      type: SHUFFLE
      streamId: "parsed_tuples_stream"

  - name: "rule --> console"
    from: "DummyRuleBolt"
    to: "ConsoleNotificationBolt"
    grouping:
      streamId: "console_stream"
      type: SHUFFLE

  - name: "rule --> email"
    from: "DummyRuleBolt"
    to: "EmailNotificationBolt"
    grouping:
      streamId: "email_stream"
      type: SHUFFLE
